# Generated by Django 5.2.6 on 2025-09-20 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bar_number',
            field=models.CharField(blank=True, help_text='Bar registration number for lawyers/attorneys', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's credentials have been verified"),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Professional license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Law firm, court, or organization name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PETITIONER', 'Petitioner'), ('RESPONDENT', 'Respondent'), ('PROSECUTION', 'Prosecution'), ('DEFENSE', 'Defense'), ('MEDIATOR', 'Mediator'), ('JUDGE', 'Judge'), ('COURT_STAFF', 'Court Staff'), ('OBSERVER', 'Observer')], default='OBSERVER', help_text='Type of user in the court hearing system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when user was verified', null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Area of legal specialization', max_length=200)),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PETITIONER', 'Petitioner'), ('RESPONDENT', 'Respondent'), ('PROSECUTION', 'Prosecution'), ('DEFENSE', 'Defense'), ('MEDIATOR', 'Mediator'), ('JUDGE', 'Judge'), ('COURT_REPORTER', 'Court Reporter'), ('BAILIFF', 'Bailiff'), ('WITNESS', 'Witness'), ('EXPERT_WITNESS', 'Expert Witness')], max_length=20)),
                ('case_number', models.CharField(help_text='Associated case number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this role assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'unique_together': {('user', 'role', 'case_number')},
            },
        ),
    ]
