# Generated by Django 5.2.3 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
