# Generated by Django 5.2.3 on 2025-10-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.CharField(help_text='Reference to user from auth service', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user_id',
            field=models.CharField(help_text='Reference to user from auth service', max_length=50, unique=True),
        ),
    ]
